### ISSUE TITLE
headless configuration not working

### ISSUE THREAD

**Issue by lionel126** [lamartire/puppeteer-page-object#12]
https://github.com/lamartire/puppeteer-page-object/blob/ed444680f25fc7999615a62515b5ce4b5d0e6492/index.js#L16
I set `options = {headless: false}  `

**Comment by lamartire** [comment]
@lionel126 , hello and thank you for issue!
Does it just not work or there is any error in runtime?

**Comment by lionel126** [comment]
just not work
if I set `options.headless=false`
`options.headless || true` still be true

**Comment by lamartire** [comment]
That was a my fault 😄 
I fixed it and published. You can update package version and use.
Have a nice day! ✨
